sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t rasgdev/docker-react -f Dockerfile.dev .

script:
    - docker run rasgdev/docker-react npm run test -- --coverage